version: '3'

services:
  taibai-redis-service:
    container_name: taibai-redis-container
    image: "redis:alpine"
    networks:
      taibai-support-network:
        ipv4_address: 172.27.1.11

  taibai-support-service:
    container_name: taibai-support-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        branch_name: "master"
    environment:
      - rabbitmq_addr
      - rabbitmq_user
      - rabbitmq_passwd
      - classroom_region
    ports:
      - "8888:8888"
    depends_on:
      - taibai-redis-service
    networks:
      taibai-support-network:
        ipv4_address: 172.27.1.12

#  taibai-consul-client:
#    image: "consul"
#    container_name: taibai-consul-client
#    networks:
#      taibai-support-network:
#        ipv4_address: 172.27.1.13
#    ports:
#      - "8300:8300"
#      - "8301:8301"
#      - "8302:8302"
#      - "8400:8400"
#      - "8500:8500"
#      - "8600:8600"
#    command: agent -server -bootstrap-expect=1 -node=taibai-consul-client-${consul_client_no} -join-wan=${consul_server_addr} -advertise-wan=${host_addr} -client=0.0.0.0 -datacenter=dc-${consul_client_no}  -ui
#
#  taibai-support-registrator:
#    image: gliderlabs/registrator
#    container_name: taibai-support-registrator
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock
#    command: "-ip ${host_addr} -tags classroom_region=${classroom_region} consul://172.27.1.13:8500"
#    networks:
#      taibai-support-network:
#        ipv4_address: 172.27.1.14
#    depends_on:
#      - taibai-consul-client

networks:
  taibai-support-network:
    ipam:
      driver: default
      config:
        - subnet: 172.27.1.0/24